package br.edu.ufersa.oportuniza.domain.entities;

public enum Course {
    CIENCIA_DA_COMPUTACAO,
    ENGENHARIA_DE_SOFTWARE,
    ENGENHARIA_DA_COMPUTACAO,
    SISTEMAS_DE_INFORMACAO,
    ENGENHARIA_CIVIL,
    ENGENHARIA_ELETRICA,
    ENGENHARIA_MECANICA,
    ENGENHARIA_QUIMICA,
    ADMINISTRACAO,
    DIREITO,
    MEDICINA,
    OUTRO
}